# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache:
  packages: true
  directories:
  - .htmlproofer-cache

# Install html-proofer
before_install:
  - gem install html-proofer
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true  # Speed up the html-proofer

script:
- Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
- htmlproofer _book

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT  # Set in the settings page of your repository, as a secure variable
  local_dir: _book
  on:
    branch: master
